### ISSUE TITLE
Documentation is unclear i cant figure out how to make it work in ST3?

### ISSUE THREAD

**Issue by maqboolkhan** [ternjs/tern_for_sublime#100]
Hi, 
Sir i really respect you as you did **`CodeMirror`** and then **`Tern`**! both are really awesome!
But my problem is that i dont know how to use **Tern** on **Sublime** 3!
I install this package then install all **`dependencies`** added `auto_complete` line in my `preferences` file but still its not working i got no luck :'(
one thing i was missing is i could not understand this line ?

`    Tern uses .tern-project files to configure loading libraries and plugins for a project. See the Tern docs for details.`

Thank you so much :)

**Comment by yavorski** [comment]
Place a `.tern-project` file in the root of your project.

It should like something like this: 

```
{
  "libs": ["browser"],
  "plugins": {
    "node": {}
  }
}
```

If this is not working, check your sublime console for errors.

**Comment by marijnh** [comment]
Tern functions even without a project file -- it just won't load any plugins or definitions (for example the definitions of the browser environment).

One thing you should always include in an issue report is _what_ is not working. What did you do? What did you expect to happen? What happened instead? "It's not working" doesn't tell us much.

**Comment by maqboolkhan** [comment]
@marijnh i have sort out all my problems :) should i change ur readme?

**Comment by maqboolkhan** [comment]
and actually it was not working without project file

**Comment by marijnh** [comment]
What was the problem?

**Comment by maqboolkhan** [comment]
sublime was not showing any suggestion but after adding project file it starts :)
means first when i write document. there was no suggestion after adding of project file it now giving me all suggestions m on windows

**Comment by marijnh** [comment]
Yes, that's the browser definitions thing I mentioned. You get, for example `[].forEach` completed by default, because it is part of JavaScript itself, but the browser environment, which defines `document`, isn't loaded by default.

**Comment by maqboolkhan** [comment]
ohhh i got now am gonna blog on your awesome work :) n m sorry
