### ISSUE TITLE
Allow completing functions as first-class objects

### ISSUE THREAD

**Issue by websash** [ternjs/tern_for_sublime#103]
Wouldn't it be better to complete just function names without parenthesis? And for the function signature to appear once you've typed invocation parenthesis? In code like this
```javascript
const even = n => n % 2 === 0
;[0, 1, 2, 3, 4].filter(even)
```
tern autocompletes `even` with parenthesis (not what's needed here and in many places like this)

**Comment by mokkabonna** [comment]
I agree, after this landed in tern, I have realized just how many times I pass around functions or access properties in the function itself.

I think more often than invoking it directly.

**Comment by marijnh** [comment]
Isn't this an option (`tern_argument_completion`) that already defaults to false?

**Comment by websash** [comment]
Not quite. I have `"tern_argument_completion": false` and tern still inserts empty parenthesis with the cursor inside after each completed function name. I have to hit backspace to clean them up every time I mean a function as first-class value, that is I don't mean to invoke it. I think the default behavior should be not to insert invocation parenthesis. E.g. MS Visual Studio Code doesn't do it and Atom's version has this option *Do not add parenthesis if method is completed* (not enabled by default though)

**Comment by marijnh** [comment]
I see, it always added those parens. That's not good. Attached patch changes this.
