### ISSUE TITLE
Error when loading

### ISSUE THREAD

**Issue by Mosho1** [ternjs/tern_for_sublime#104]
I'm getting these in ST console:

	TernJS: Loading PyV8 binary from https://raw.github.com/emmetio/pyv8-binaries/master/pyv8-win32-p3.zip
	Package Control: Finished replacing Git.sublime-package
	Syncing project C:\repositories\new-homepage\new-homepage.sublime-project
	Starting TernJS server for C:\repositories\new-homepage\new-homepage.sublime-project with 1 libs and 12518 files
	Syncing project C:\repositories\react-style\react-style.sublime-project
	Starting TernJS server for C:\repositories\react-style\react-style.sublime-project with 1 libs and 17276 files
	Syncing project C:\client.sublime-project
	Starting TernJS server for C:\client.sublime-project with 1 libs and 224 files
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\bin\\generate-identifier-regex.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\bin\\build-acorn.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\dist\\acorn.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\dist\\acorn_loose.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\dist\\walk.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\statement.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\options.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\parseutil.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\tokenize.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\state.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\location.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\expression.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\node.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\lval.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\identifier.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\locutil.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\util.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\index.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\tokencontext.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\tokentype.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\whitespace.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\bin\\acorn.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\index.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\state.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\statement.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\expression.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\acorn_loose.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\parseutil.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\loose\\tokenize.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\acorn\\src\\walk\\index.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\glob.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\examples\\g.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\examples\\usr-local.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\minimatch.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\test\\brace-expand.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\test\\basic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\test\\defaults.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\test\\extglob-ending-with-state-char.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\node_modules\\minimatch\\test\\caching.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\stat.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\zz-cleanup.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\globstar-match.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\cwd-test.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\root-nomount.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\readme-issue.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\00-setup.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\mark.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\root.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\bash-comparison.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\nocase-nomagic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\pause-resume.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\glob\\test\\new-glob-optional-options.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\inherits\\test.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\inherits\\inherits.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\inherits\\inherits_browser.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\lru-cache\\lib\\lru-cache.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\lru-cache\\test\\foreach.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\lru-cache\\test\\memory-leak.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\lru-cache\\test\\basic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\lru-cache\\test\\serialize.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\minimatch.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\test\\brace-expand.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\test\\basic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\test\\defaults.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\test\\extglob-ending-with-state-char.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\minimatch\\test\\caching.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\sigmund\\bench.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\sigmund\\sigmund.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\sigmund\\test\\basic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\doc\\demo\\polyfill.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\doc\\demo\\underscore.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\doc\\demo\\demo.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\tern.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\comment.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\signal.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\def.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\infer.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\condense.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\lib\\typescript.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\node_resolve.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\modules.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\requirejs.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\angular.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\es_modules.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\doc_comment.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\commonjs.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\complete_strings.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\plugin\\node.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\timeout.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\runcases.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\reload.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\fragments.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\util.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\phantom_object.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\infinite-expansion.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\catch_error.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\hint-objlit.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\arrow.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\arguments.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\new_array.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\findref.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\global_this.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\super.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\es6-features.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\in_comment.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\jsdoc.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\span_from_def.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\angular_service.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\generic_each.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_exports.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\map.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\protoname.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_origin_paths.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\replace_bogus_prop.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\extends.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\set.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\browser.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\proto.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\symbol.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\underscore.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\block_scope.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\objectlit.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\object_create.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\plus.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\copyprops.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\autothis.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\order_of_definition.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\objnames.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\array_holes.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\finddef.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\simple_generic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\hint_simple.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\contextcomplete.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\bind.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\generator.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\promise.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\class.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\empty_overridden_prop.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\merge.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\hint_browser.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\indirect_class.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\simple.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\hint_ecma5.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\builtins.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\new_to_prototype.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\complete_strings.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\jquery_event.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\def_type_string.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\docstrings.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\computedprop.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\destructure.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\defineProperty.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\effects.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\for_of.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\cautiouspropagation.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\template.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\fn_arguments.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\ctorpattern.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\mixin.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\getter.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\blowup.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\angular\\filters.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\angular\\config.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\angular\\main.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\es_modules\\blah.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\es_modules\\foo.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\es_modules\\main.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\es_modules\\reexp.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\exportfunc.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\localfile.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\main.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\dir\\index.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\dir\\lib\\relative.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node\\dir\\lib\\other.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\secondfile.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\reassign_exports_to_required.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\doc.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\reassign_exports.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\mainfile.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\a.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\dir1\\index.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\node_modules\\mod1\\node_modules\\subdep1\\subdep1.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\main.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\named.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\simplifiedcommon.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\bar.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\module_exports.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\useexports.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\baz.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\foo.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\requireme.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\func.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs\\subdir\\zap.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\cases\\requirejs_config\\main.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\requirejs_primitive.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\node_fn_export.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\recursive.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\node_require_private.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\node_export_function_a.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\proto.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\ignore_newer.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\add_to_old.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\extend_foo.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\requirejs_empty_deps.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\function_prop.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\requirejs_const.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\ref_in_type.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\requirejs_dep.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\array.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\basic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\double_ref.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\fn.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\ref_to_old.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\angular_simple.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\uniontype.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\node_simple.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\requirejs_setup.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\generic.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\condense\\node_other_module_type_ref.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\tern\\test\\data\\large.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\typescript\\bin\\tsc.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\node_modules\\typescript\\bin\\typescript.js'
	[Errno 22] Invalid argument: 'C:\\C:ackages\\tern_for_sublime\\test\\demo\\simple\\test.js'

**Comment by marijnh** [comment]
tern_for_sublime does not depend on PyV8. You are probably using the other, deprecated Tern plugin. Switch to this one, and see if that goes better.
