### ISSUE TITLE
JSX tooltip problem fn() -> bool 

### ISSUE THREAD

**Issue by max-mykhailenko** [ternjs/tern_for_sublime#105]
When write JSX always see this tooltip. How I can remove it?

![image](https://cloud.githubusercontent.com/assets/1213198/11530835/a50af5fc-9900-11e5-94a9-cc0689931486.png)

**Comment by marijnh** [comment]
Attached patch should fix this

**Comment by marijnh** [comment]
Err, I meant patch https://github.com/ternjs/tern/commit/15e3d27b9ed1207337e0592bb05de50b9eb7b95f , which I _tried_ to attach

**Comment by max-mykhailenko** [comment]
Thanks!
