### ISSUE TITLE
Javascript: "FunctionDeclaration" error when editing function's return block

### ISSUE THREAD

**Issue by rbarillec** [ternjs/tern_for_sublime#110]
Sublime Text v. 2.0.2., build 2221
Mac OSX 10.9.5

How to reproduce:

- Open Sublime Text
- Create a new file
- Save file as "test.js" (to set as javascript)
- Type in the following: 
```
function foo() {}
```  
- Inside the brackets, add a return block: 
```
function foo(){
   return {}
}
```
- Inside the `return` block, type any character:
```
function foo(){
   return {
      a
   }
}
``` 

The following exception is thrown: 

TypeError: Object #<Object> has no method 'FunctionDeclaration'

![screen shot 2015-12-24 at 10 39 41](https://cloud.githubusercontent.com/assets/1492063/11993326/cd865900-aa2f-11e5-9c37-bb64e6f50fe6.png)
[apple_error_log.txt](https://github.com/ternjs/tern_for_sublime/files/71644/apple_error_log.txt)

Cheers,
Remi

**Comment by marijnh** [comment]
I can't reproduce this. What version of Tern are you on?

**Comment by rbarillec** [comment]
Hi Marijn,

I'm not sure, I may have been using an older version? Let me check with the latest version and get back to you.

**Comment by rbarillec** [comment]
Hi Marijn,

Updating to the latest version of TernJS seems to have removed the issue. Thanks for your help, marking as closed.

Cheers,
Remi
