### ISSUE TITLE
autocomplete does not works on ST3/Windows 7

### ISSUE THREAD

**Issue by nosuchip** [ternjs/tern_for_sublime#117]
I have brand bw installation of ST3. Adding `tern_for_sublime` package and manually install required Node packages (as described in popup appeared after installation). In log after restart I see `reloading plugin tern_for_sublime.tern`. In project file added lines:
```
    "ternjs": {
        "include":["**/**.js"],
        "libs": ["browser", "jquery"]
    }
```
Opening random `js` file and writing `document.` I expecting that only document-related values appeas. but a see everything but nothing related to document (for example `createElement` missing).

Also looks like tern does not loads other JS files because once I tried to get autocomplete on some javascript classes I got only default autocomplete tooltip (suspect - ST3's one).

Also does not works Jquery autocomplete: adding `$.` in JS file and expecting, for example, `toggle` appears. But it doesn't.

**Comment by marijnh** [comment]
You seem to be putting options that Tern expects in its `.tern-project` file into your ST config. That doesn't work.
