### ISSUE TITLE
no jQuery completion in document ready when using function($)

### ISSUE THREAD

**Issue by PixelT** [ternjs/tern_for_sublime#119]
no jQuery completion when use:
```
jQuery(document).ready(function($) {
$(element).
```
in other ways work OK:
```
jQuery.noConflict();
jQuery(document).ready(function() { 
$(element).
```
```
$(document).ready(function() {
$(element).
```

**Comment by tansongyang** [comment]
If I'm not mistaken, [this commit in Tern](https://github.com/ternjs/tern/commit/f9b28c99e001d4098a7abec48884888ba81a3726) should address the issue. @marijnh can you confirm?

**Comment by marijnh** [comment]
It does -- it was supposed to refer to this issue, but I got the issue reference in the commit message wrong
