### ISSUE TITLE
Freezing whole Sublime after installation

### ISSUE THREAD

**Issue by FredyC** [ternjs/tern_for_sublime#131]
I just see at the bottom "Loading PyV8 binary, please wait" and otherwise it's frozen. I tried waiting like 5 minutes, but no luck. Might be related that I don't have Python installed? And I don't plan to install it, I don't like global dependencies.

Windows 10 x64
Sublime Text 3114

**Comment by marijnh** [comment]
This plugin doesn't use PyV8, so you appear to be using the other, deprecated Tern plugin, and this issue doesn't apply to this repository.
