### ISSUE TITLE
Doesn't auto complete basic built-in JS

### ISSUE THREAD

**Issue by geligelu** [ternjs/tern_for_sublime#135]
Hey there, 

I might be doing something wrong, but I followed the instructions to a 'T' for installing and getting up and running, and auto complete is working, but only for more obscure or seemingly random stuff. 

Example, from your instructions suggests ``document.addEv`` should autocomplete for ``document.addEventListener()``, but if you look the screenshot provided, it doesn't even want to autoocomplete ``document``, let alone ``addEventListener``:

<img width="489" alt="somefile_js_and_new_issue_ _ternjs_tern_for_sublime" src="https://cloud.githubusercontent.com/assets/6688676/18555883/0a6ad6d2-7b9c-11e6-933a-8f050fa8e75a.png">

<img width="139" alt="somefile_js" src="https://cloud.githubusercontent.com/assets/6688676/18555979/74704eae-7b9c-11e6-9dd9-e78f388839e8.png">

<img width="1440" alt="screen shot 2016-09-15 at 23 31 10" src="https://cloud.githubusercontent.com/assets/6688676/18556001/8f57f28a-7b9c-11e6-9b84-36f03fe4fd09.png">

Any ideas why this might be happening? Why does it not seem to have the full set of javascript available?

**Comment by marijnh** [comment]
Sounds like you aren't loading the browser defs. Create a `.tern-project` file with `{"libs": ["browser"]}` in it.
