### ISSUE TITLE
Still can't get autocomplete to work

### ISSUE THREAD

**Issue by basvdwollenberg** [ternjs/tern_for_sublime#145]
`Tern.sublime-settings`:
```json
{
  "tern_argument_hints": true,
  "tern_argument_completion": true
}
```

Added this to `Preferences.sublime-settings`:
```json
[
	{
		"characters": "<",
		"selector": "text.html"
	},
	{
		"characters": ".",
		"selector": "source.js"
	}
]
```

Installed packages:
```json
"AdvancedNewFile",
"AutoPEP8",
"BracketHighlighter",
"Color Highlighter",
"DoxyDoxygen",
"Emmet",
"ESLint-Formatter",
"ExpandRegion",
"Git",
"GitGutter",
"Material Theme",
"Material Theme - Appbar",
"Missing Palette Commands",
"Package Control",
"SideBarEnhancements",
"Stylus",
"SublimeLinter",
"SublimeLinter-contrib-eslint",
"SublimeLinter-contrib-stylint",
"Sync Settings",
"SyncedSideBar",
"tern_for_sublime",
"Vue Syntax Highlight",
"zz File Icons"
```

Also tried adding a `.tern-project` file in my project root directory:
```json
{
  "libs": [],
  "plugins": {
    "node": {}
  }
}
```

- Ran `npm i` in the `tern_for_sublime` directory
- No errors in the console (loads fine: `reloading plugin tern_for_sublime.tern`)
- All of the key bindings work fine

I have no idea what I could be doing wrong.

**Comment by IvoVermeer** [comment]
Try to do a simple test:

Start in an empty folder with a .tern-project file::
```JSON
{
	"libs": [
		"browser"
	]
}
```
and a new script file:

```javascript
function testLog (string, object) {
  console.log(string);
  console.log(object)
}

test // <== should now autocomplete to 'testLog (fn/2), testLog (fn/1), etc'
```

If the above doesn't work and just to make sure none of the other packages are conflicting, backup your sublime `User` folder and remove all but `Packagecontrol` and `tern_for_sublime` from the `Package Control.sublime-settings`.

My setup is working fine, I have the following packages:
```
"AutoAligner",
"AutoFileName",
"Bootstrap 3 Snippets",
"DocBlockr",
"ESLint-Formatter",
"Git",
"HTML-CSS-JS Prettify",
"JavaScript Snippets",
"Markdown Preview",
"MarkdownEditing",
"npm",
"Package Control",
"PlainTasks",
"SideBarEnhancements",
"Sublime Tutor",
"SublimeLinter",
"SublimeLinter-contrib-eslint",
"tern_for_sublime",
"Theme - Soda"
```

**Comment by basvdwollenberg** [comment]
Ah, so it did work when I created a new folder in a new Sublime window, but for some reason it wouldn't work on an existing project. I added my existing project to the new window and now it works. Thanks!

**Comment by IvoVermeer** [comment]
No problem, you're welcome!
