### ISSUE TITLE
how to set preview parameters directly not (fn/1,2,3,...)

### ISSUE THREAD

**Issue by easyfrog** [ternjs/tern_for_sublime#148]
If this can directly preview parameters will more friendly then (fn/1,2,3,...).

like this one:
![557ea7de-c8e6-11e5-8019-aebe937aad18](https://cloud.githubusercontent.com/assets/10724325/20334602/5c9ce3e8-abf6-11e6-98f0-6d1364888fab.png)

**Comment by marijnh** [comment]
Where does it say `fn/1,2,3`, and what do you mean by directly previewing parameters?

**Comment by easyfrog** [comment]
![ternjs](https://cloud.githubusercontent.com/assets/10724325/20381065/b5d55752-ace0-11e6-80e6-572b17f6c613.png)
Well, I have to modify the 'tern.py' file by myself, if it is a Function, it can directly preview some of its parameters now, rather than (fn/1) (fn/2)... And align the parameters to the right will looks more comfortable.

here is the tern.py I modified:
[tern.py.zip](https://github.com/ternjs/tern_for_sublime/files/596857/tern.py.zip)

**Comment by easyfrog** [comment]
Now I append the function's return type directly to sublime completion list.
![ternjs2](https://cloud.githubusercontent.com/assets/10724325/20455420/ae517c42-ae96-11e6-9c61-947a6cdb7e33.png)

![ternjs4](https://cloud.githubusercontent.com/assets/10724325/20455574/03491874-ae9a-11e6-94ba-fa7599cb822f.png)


here is the tern.py I modified:
[tern.py.zip](https://github.com/ternjs/tern_for_sublime/files/601439/tern.py.zip)

**Comment by marijnh** [comment]
If you want to submit code, please use a github pull request, not zip files.

**Comment by marijnh** [comment]
See #152
