### ISSUE TITLE
Is the variables must in global scope could be analyze by terns?

### ISSUE THREAD

**Issue by easyfrog** [ternjs/tern_for_sublime#149]
src/game.js
`var Game = function() {...};`

.tern-project
`{
"loadEagerly": [
		"src/*.js"
	]
}`

main.js
`var g = new Game();`
`g.`
there is no completion suggestion.

I must change the game.js from  `var Game = ` to `window.Game = ` . then could get suggestion correct.

So is the variables  must in global scope ?

**Comment by easyfrog** [comment]
OH.... when I remove "node" plugins then it works.
 so the `var Game =` is conflict to the node plugin?

**Comment by marijnh** [comment]
The node plugin isolates files into CommonJS modules, so they don't share a top scope.
