### ISSUE TITLE
No subprocess.check_output in the Sublime 2.0 subprocess module

### ISSUE THREAD

**Issue by martineno** [ternjs/tern_for_sublime#15]
The subprocess module in Sublime Text 2.0 build 2217 doesn't have the check_output function.

This causes a problem with the tern.py script, which errors out with an error on line 474 of the `tern.py` script.

This means that it is not possible to install the plugin using the tern.py script.

It seems that all the plugin python files always run with Python 2.6 in Sublime Text 2. The check_output wasn't introduced until 2.7 according to the Python docs.

**Comment by tansongyang** [comment]
@martineno The pull request you linked to was closed. Has your issue been resolved?
