### ISSUE TITLE
Connection reuse error

### ISSUE THREAD

**Issue by easyfrog** [ternjs/tern_for_sublime#153]
Make sublime into background(switch to other app) and wait a while.  Go back to sublime and type some codes to invoke completion then give me a Error alert dialog.

If pressed "Cancel" it will shown every time I type "."  
Must restart the sublime to resolve it.

![reuse](https://cloud.githubusercontent.com/assets/10724325/20524163/15dbeeb0-b0f4-11e6-8c84-857ce0225ca9.png)

**Comment by karolyi** [comment]
same here, can confirm.

it's the background process that dies for some reason. trying to start it in debug mode and post tracebacks here.

**Comment by marijnh** [comment]
The server intentionally shuts itself down after 5 minutes, by default. But the plugin should try to restart it before bothering the user with an error, which is apparently broken.

**Comment by easyfrog** [comment]
change tern.py line 268: 

from :
`raise Req_Error((hasattr(error, "read") and error.read().decode("utf-8")) or error.reason)`
back to :
`raise Req_Error(error.read().decode("utf-8"))`

just give me a  `time out` alert dialog and close it  could continue use. don't need restart sublime.

**Comment by marijnh** [comment]
> change tern.py line 268:

That line doesn't look like that anymore in the current source code.

**Comment by easyfrog** [comment]
Right it is:
`raise Req_Error((hasattr(error, "read") and error.read().decode("utf-8")) or str(error.reason))`

But how to avoid this issue?

**Comment by marijnh** [comment]
Could you try with patch b3c1b3a ?

**Comment by easyfrog** [comment]
> Could you try with patch b3c1b3a ?

Yeah~  its just **TIME OUT** alert dialog now. do not need restart.

But this **TIME OUT** dialog is also annoying.
