### ISSUE TITLE
tern_jump_to_def to another file

### ISSUE THREAD

**Issue by mrkafk** [ternjs/tern_for_sublime#154]
Apparently the plugin can't find the definition in another file unless the definition has been sought for first in that other file.

Steps to reproduce:

1. Create two files: `a.js`, `b.js`.

2. Set a variable `var colorValues = [];` in `a.js`.

3. Switch to file `b.js`.

4. Restart ST3.

5. In file `b.js` type `colorValues` and then try jumping to its definition (using `alt+.`) when cursor is on this word. Result: a popup "Could not find a definition".

It works when:

6. Switch to file `a.js`, type `colorValues`, jump for the definition while cursor is on this word.

7. Switch to file `b.js`, jump for the definition on `colorValues` typed in there. Result: ST3 switches to `a.js` and correctly places the cursor on the definition.

ST3, latest `tern_for_sublime` as of today. Platform: Ubuntu Linux x64.

**Comment by marijnh** [comment]
The server loads files lazily, so unless you've touched the file in this session, it won't know about it. You can use the `loadEagerly` config option or a module system to work around this.
