### ISSUE TITLE
Not getting DOM autocompletion 

### ISSUE THREAD

**Issue by saketh-bobby** [ternjs/tern_for_sublime#157]
Installed tern for sublime text ,core javascript autocompletion works but DOM for methods like getElementById etc autocompletion is not available.Is this intentional?

**Comment by marijnh** [comment]
Enable the 'browser' defs in your project configuration. See [here](http://ternjs.net/doc/manual.html#configuration) for docs.

**Comment by saketh-bobby** [comment]
Okay thanks for the pointers now working like a charm. But autocompletion for addEventListener, onclick  etc still not available any config to be done for that or just create my own snippets for them?

**Comment by marijnh** [comment]
Can you show an example where you'd expect a completion for `addEventListener` but aren't getting it?

**Comment by saketh-bobby** [comment]
As shown in the screenshot 

> **No available completion**


![auto](https://cloud.githubusercontent.com/assets/12474004/21581437/0c404e7c-d058-11e6-990d-09c9a9911890.png)

My **Tern.sublime-settings** file:
![settings](https://cloud.githubusercontent.com/assets/12474004/21581442/48d4bbca-d058-11e6-86d8-bd683cef00d4.png)

My **.tern-project file** @ /tern-for-sublime/node_modules/tern

![tern](https://cloud.githubusercontent.com/assets/12474004/21581451/71bdaab0-d058-11e6-88e5-ef67c610adf5.png)

## Previously thought some DOM methods working but were actually working due to other package but turns out all DOM methods are not working with tern !!!

**Comment by marijnh** [comment]
Your project file isn't being picked up. Probably because you didn't actually put it in your project dir. If you're trying to create a system-wide config, create a `.tern-config` file in your home directory.

**Comment by saketh-bobby** [comment]
Yup got it working !!! Thought it might be a bug.Weird earlier es6 auto-complete working well and browser.json not getting picked up.Again,I don't know the implementation so anyways awesome job you've done with Tern and I loved your Eloquent book.Thanks!!
