### ISSUE TITLE
Wrong completion when file has emoji

### ISSUE THREAD

**Issue by Klaster1** [ternjs/tern_for_sublime#159]
**What happens:**
Weird completion results when document has emoji (commented or not).
![actual](http://i.imgur.com/ELtheNF.png)
```
const a = 'a'
const b = '🍆'
a.
```

**Expected behavior:**
Same completion as on this image:
![expected](http://i.imgur.com/CoE80Zg.png)

**Comment by marijnh** [comment]
The problem appears to be that editors, sanely, count positions in characters, but Tern, at the moment, counts in UTF16 units, so astral plane characters will count as two, and throw off all positions after them.

This is a bug in Tern, and it should be adjusted to treat positions received from and sent to the outside world as character offsets.

**Comment by marijnh** [comment]
Attached patch seems to solve the issue in Sublime Text. (Emacs is still broken because Emacs' JSON library seems to not be aware that astral plane characters exist.)

**Comment by marijnh** [comment]
Err, I meant patch https://github.com/ternjs/tern/commit/3cfb76a2734a840ce3543ffbe46825b44587a892

**Comment by marijnh** [comment]
(It does work in Emacs version 25, which fixes the JSON encoder.)
