### ISSUE TITLE
Problem with  Object.assign function

### ISSUE THREAD

**Issue by easyfrog** [ternjs/tern_for_sublime#160]
When I use `Object.assign` to mixin multiple prototypes (more then 1).  

like this: 
`Object.assign(myClass.prototype, firstClass.prototype, secondClass.prototype);`

The problem is ternjs only could analyze the `firstClass`'s function. and  the `secondClass` 's functions cannot be shown in the completion list.  So is it a bug ?

![assignbug](https://cloud.githubusercontent.com/assets/10724325/23094108/a9c49d74-f62d-11e6-9ab3-1c2b54e66393.png)

**Comment by marijnh** [comment]
Attached patch defines the method to also copy properties from the 3rd and 4th args, if given. That's still not entirely correct, but should cover most cases.
