### ISSUE TITLE
Definition about ES6 .tern-project file

### ISSUE THREAD

**Issue by easyfrog** [ternjs/tern_for_sublime#161]
If I use 'es_modules: {}` in `plugins` to handle es6's `import` and `export`. and the `loadEagerly` is necessary?

<img width="448" alt="qq20170219-093345 2x" src="https://cloud.githubusercontent.com/assets/10724325/23098372/90d1f876-f686-11e6-854a-e277dcd10592.png">

**Comment by marijnh** [comment]
If you load files through a module system, you don't have to tell Tern about them with `loadEagerly`.

**Comment by easyfrog** [comment]
But if I don't write `loadEagerly` in `.tern-project`, tern wile not analyse any module at all.

look this:

1. write `loadEagerly`:
![with1](https://cloud.githubusercontent.com/assets/10724325/23109824/47f30196-f757-11e6-8c77-9ff101d97ed3.png)
and give me correctly result:
![withloadeagerly](https://cloud.githubusercontent.com/assets/10724325/23109833/5a21f674-f757-11e6-95a8-e5d13d1d2408.png)

2. without `loadEagerly`:
![without1](https://cloud.githubusercontent.com/assets/10724325/23109844/75ca5d9e-f757-11e6-9183-33ac2b24a32d.png)
and without any tips.
![without2](https://cloud.githubusercontent.com/assets/10724325/23109853/8c825f28-f757-11e6-842f-2bb108bf5597.png)
