### ISSUE TITLE
Trigger module name autocomplete

### ISSUE THREAD

**Issue by seanders** [ternjs/tern_for_sublime#168]
Hello,

I'm having trouble completing module paths like I see working in this [demo](http://ternjs.net/doc/demo/index.html#ES6). I'm using Sublime.

I spun up the `tern` server locally with the `--verbose` flag. I don't see a request coming in for trying to resolve the module path.

For example:
Say I have this:
src/
  |..Foo.js
  |..Bar.js

```javascript
// Foo.js
export default () => {}
```

```javascript
// Bar.js
import Foo from './' //Manually triggering the autocomplete after `/` isn't returning `Foo`
```

Heres my config:
```json
{
  "ecmaVersion": 7,
  "plugins": {
    "webpack": {
      "configPath": "./config/webpack.config.dev.js"
    }
  },
  "loadEagerly": ["src/**/*.js"],
  "dontLoad": ["node_modules/**"]
}
```

Looking up module definitions and autocompletions of attributes on imported modules is working find, however. Any help would be greatly appreciated.

**Comment by marijnh** [comment]
It seems the ST plugin is explicitly disabling completions inside strings (via #12). Attached patch removes this, since it breaks features like this.
