### ISSUE TITLE
Package import autocompletion causes duplicate quotes

### ISSUE THREAD

**Issue by TheReturningVoid** [ternjs/tern_for_sublime#171]
Using any autocompletion of a node module installed with npm causes the quotes used to be duplicated.

Example:
![GIF recording of issue](https://i.imgur.com/PEkDNUU.gif)

This also occurs for imports of the form `const React = require('react')`.

**Comment by easyfrog** [comment]
Yes same issue:
![error](https://user-images.githubusercontent.com/10724325/30424178-aba80bce-9977-11e7-8441-d3d553f9160a.gif)

**Comment by easyfrog** [comment]
Yes,  same issue:
![image](https://user-images.githubusercontent.com/10724325/30424286-12710cca-9978-11e7-9053-179b5889fa0a.gif)

**Comment by simonhaenisch** [comment]
anyone working on this?

**Comment by davae1an** [comment]
Can confirm this issue also

**Comment by codeHamster9** [comment]
yeap i'm in on this too...any solution in sight ?

**Comment by simonhaenisch** [comment]
My current solution was switching to VS Code for the better eco system. It has built-in code analyzing/intelligence for Typescript which can be enabled for Javascript as well with

```json
{
  "javascript.implicitProjectConfig.checkJs": true
}
```

I still use ST for its speed though and would often prefer it, but too many plugin devs switched to Code. And Code definitely has its benefits.

**Comment by philipbordallo** [comment]
A quick fix for this is to remove any `'` by adding `.replace("'", "")` to the end of https://github.com/ternjs/tern_for_sublime/blob/91a27a39b1b0a33a9043aa685e1ee48c64a58274/tern.py#L438

**Comment by berkandirim** [comment]
> A quick fix for this is to remove any `'` by adding `.replace("'", "")` to the end of
> 
> [tern_for_sublime/tern.py](https://github.com/ternjs/tern_for_sublime/blob/91a27a39b1b0a33a9043aa685e1ee48c64a58274/tern.py#L438)
> 
> Line 438 in [91a27a3](/ternjs/tern_for_sublime/commit/91a27a39b1b0a33a9043aa685e1ee48c64a58274)
> 
>  rec_name = rec.get('name').replace('$', '\\$')

This only removes the single quotes but still adding the extra '../' It should be replacing what you typed in quotes completely.

**Comment by ViggoV** [comment]
Any news on this issue? It is incredibly annoying..
