### ISSUE TITLE
Turn off the triggers after ";"

### ISSUE THREAD

**Issue by kamranpoladov** [ternjs/tern_for_sublime#182]
Auto complete triggers after dot are pretty useful, however, when they appear after ";" (end of the line) or after I have chosen the suggested function from the dropdown list. In these cases they really slow down the work pushing me to close this dropdown list every time. I the attachments I provided both cases described above.

<img width="124" alt="screen shot 2018-08-23 at 21 20 59" src="https://user-images.githubusercontent.com/42556944/44541315-a1c79500-a71a-11e8-880d-bb939350401b.png">
<img width="420" alt="screen shot 2018-08-23 at 21 21 04" src="https://user-images.githubusercontent.com/42556944/44541316-a1c79500-a71a-11e8-9ad8-cc42fe7fa184.png">
<img width="350" alt="screen shot 2018-08-23 at 21 21 19" src="https://user-images.githubusercontent.com/42556944/44541317-a1c79500-a71a-11e8-988e-466eef7ed1e9.png">

I don't know why I can't upload fourth screenshot, but there is pretty much the same thing as on second one:
After choosing **push** method the same thing occurs on the screen.

**Comment by mrG0bliN** [comment]
@kamranpoladov confirm!

**Comment by othree** [comment]
I can't reproduce this issue now(using latest tern). Can you try again?
