### ISSUE TITLE
How to surpress "timed out" errors?

### ISSUE THREAD

**Issue by OliverJAsh** [ternjs/tern_for_sublime#32]
I get "timed out" errors quite often (every 5 minutes or so). I'm using the Node plugin.

**Comment by tansongyang** [comment]
Closing this issue because commit [659ff49](https://github.com/ternjs/tern_for_sublime/commit/659ff49f068dfa5b57aed778c20acf7edbc54611) provides a workaround.

**Comment by skizzo** [comment]
> Closing this issue because commit [659ff49](https://github.com/ternjs/tern_for_sublime/commit/659ff49f068dfa5b57aed778c20acf7edbc54611) provides a workaround.

Cool, any instructions about how to use this workaround?
