### ISSUE TITLE
Sublime 3 crashing with TernJS.

### ISSUE THREAD

**Issue by pnunn** [ternjs/tern_for_sublime#37]
I just installed this package end TernJS following the directions given but Sublime is now crashing.

The console has the following.

SyntaxError: Unexpected token < ( plugin/meteor.js @ 6 : 0 )  -> <!DOCTYPE html>
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

Any ideas??

OK, seems to be a problem with TernJS not this package.. mixed issues by the looks. Removed TernJS and it seems to be good now. Thanks.

**Comment by max-mykhailenko** [comment]
My sublime freeze without any error

Config file
```
{
  "libs": [
    "browser"
  ],
  "loadEagerly" : [
    "**/*.js",
    "**/*.jsx"
  ],
  "dontLoad" : [
    "/node_modules/**/*"
  ],
  "plugins": {
    "doc_comment": {}
  }
}
```

**Comment by max-mykhailenko** [comment]
My error doesn't appear again on fresh installation.

**Comment by marijnh** [comment]
Strange. Closing until further info comes in.
