### ISSUE TITLE
Hints Popup Custom Styling

### ISSUE THREAD

**Issue by FreaKzero** [ternjs/tern_for_sublime#68]
Hi thought about a Custom Popup styling Feature, since its just plain Textcontent maybe we can load that css content in the initialisation of the plugin and concat them together in the render_tooltip method. Did it hardwired for a Monokay flavour.
![screen](https://cloud.githubusercontent.com/assets/6339036/6964449/82cf3812-d949-11e4-9ddf-af749967c404.png)

**Comment by marijnh** [comment]
Unless there is a sane way to automatically adjust to any theme, I think this is out of scope for this project (I certainly am not going to special-case individual themes).

**Comment by linde12** [comment]
>By default the popup will be run with a user style sheet matching the font size and font family that the View is using, but this can be overridden via regular CSS.

See: https://www.sublimetext.com/forum/viewtopic.php?f=2&t=17583

However default style is horrible imo, i like what you've done. Vintage(default) theme in ST3 has white borders so when i tried to replicate what you did it looked horribly though. Wish you could change everything, including the borders, with custom CSS.

**Comment by FreaKzero** [comment]
i have done a fork which uses styles from any selected theme - its just quite buggy right now (some things dont work on all themes...) and i didnt had the time yet to work further on this.

**Comment by linde12** [comment]
Ah, i'll have to check it out!

**Comment by PixelT** [comment]
I don't know it exactly a bug, but:

![](http://i.imgur.com/bHSUwfZ.png)

Should the tooltip have auto width / height - or the long string (in example below is url to doc) should be wrap.

**Comment by tansongyang** [comment]
The most recent commit should address @PixelT 's issue. The URL has been shortened, so that the rest wraps normally.

Closing this issue now. @FreaKzero , if you believe your fork is in a good state, feel free to submit a pull request.

**Comment by FreaKzero** [comment]
@tansongyang I did a complete new fork since the codebase changed (renderer) the only thing i would need is someone who can test this in sublime 2 before i make a Pull Request ?

Tested that thing now with multiple Themes - also with colorsublime themes, 1 out of 10 isnt working (when it isnt working, it falls back to default colorscheme)

![win](https://cloud.githubusercontent.com/assets/6339036/11783354/1e10fd3c-a277-11e5-842a-e9ffbf0a6281.jpg)

**Comment by tansongyang** [comment]
@FreaKzero I just tried this in Sublime Text 2, and tern_for_sublime functionality is broken for me. Does the same thing happen to you?

ST2 doesn't support the panel at all, so make sure your code only gets run in ST3.
