### ISSUE TITLE
Please consider using a separate preferences file

### ISSUE THREAD

**Issue by N4M3Z** [ternjs/tern_for_sublime#77]
Please consider using a separate preferences file instead of putting preferences into Sublime's default `Preferences.sublime-text` as this file is often modified and automatically generated by a multitude of packages and hence it is not possible to keep comments in it. Also, it just makes sense to have a separate configuration file for the package with at least 2 configurable options.

**Comment by marijnh** [comment]
Want to submit a pull request (that is backwards-compatible, so that it still picks up setting specified the 'old' way)? I don't have much experience with ST's plugin system, and just did what I saw other plugins do.

**Comment by N4M3Z** [comment]
It should be trivial. I will try to have a look at different packages and just duplicate what they are doing. Can't promise any timescale though.

**Comment by tansongyang** [comment]
Closing because this has been addressed in a pull request.
